name: prod-ci

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DOTNET_VERSIONS: |
    6.0.x
    7.0.x
    8.0.x
    9.0.x

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      packages: write

    steps:
      # Setup
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSIONS }}

      # Build
      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      # Test
      - name: Run tests
        run: dotnet test --no-restore --configuration Release --verbosity normal

      # Publish
      - name: Extract version from csproj
        id: get_version
        run: |
          VERSION=$(grep -oP '<Version>\K[^<]+' DecoratR/DecoratR.csproj)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create NuGet package
        run: dotnet pack --no-build --configuration Release --output ./artifacts

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          generate_release_notes: true
          files: ./artifacts/*.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NuGet.org
        run: dotnet nuget push "./artifacts/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        if: success()
