name: Validate Renovate Config

on:
  push:
    paths:
      - "renovate.json"
      - "renovate-*.json"
      - ".github/renovate*.json"
  pull_request:
    paths:
      - "renovate.json"
      - "renovate-*.json"
      - ".github/renovate*.json"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Renovate Config
        uses: rinchsan/renovate-config-validator@v0.2.0
        with:
          pattern: "renovate*.json"
